---
apiVersion: apps/v1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  name: friendly-k8s-optimized       # Name of my Go application
spec:
  replicas: 2                    # Keep 2 pods alive and running
  selector:
    matchLabels:
      app: friendly-k8s-optimized    # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: friendly-k8s-optimized 
    spec:                        # Specs for the container which will run in the Pod
      containers:
      - name: friendly-k8s-optimized
        image: zjhans/friendly-k8s-optimized:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080
#Start service configuration
---
apiVersion: v1
kind: Service
metadata:
    name: friendly-service
spec:
    type: NodePort
    ports:
    - name: http
      nodePort: 30002
      port: 8080
      targetPort: 8080
    selector:
      app: friendly-k8s-optimized
